version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../public/:/var/www/html

  php:
    container_name: php
    image: php:7.4-fpm
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../:/var/www

